name: nodeJs CI

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

jobs:
  auto-format:
    name: Auto format
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install dependencies
        run: yarn add prettier

      - run: yarn run format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Apply formatting changes
