export const vuilders = [
    {
        '_id': '1',
        'name': 'vuilder_1',
        'image': '/images/empty-profile.png',
        'header': 'Im a Vuilder! This is my header!',
        'blog' : 'isque ac enim. Pellentesque ullamcorper ex ac nibh gravida aliquet non a sem.',
        'link': 'www.vuilder1.com',
        'minted': "false",
        'mint_date': 'Not Minted Yet',
        'current_price' : 0.003,
        'sold': 0,
        'vft_reserve': 1000,
        'vite_reserve': 0.3
    },
    {
        '_id': '2',
        'name': 'vuilder_2',
        'image': '/images/empty-profile.png',
        'header': 'this is my header',
        'blog' : 'isque ac enim. Pellentesque ullamcorper ex ac nibh gravida aliquet non a sem.',
        'link': 'www.vuilder2.com',
        'minted': "true",
        'mint_date': '05/08/2021',
        'current_price' : 77.4,
        'sold': 258,
        'vft_reserve': 742,
        'vite_reserve': 0.3
    },
    {
        '_id': '3',
        'name': 'vuilder_3',
        'image': '/images/empty-profile.png',
        'header': 'this is my header',
        'blog' : 'isque ac enim. Pellentesque ullamcorper ex ac nibh gravida aliquet non a sem.',
        'link': 'www.vuilder3.com',
        'minted': "true",
        'mint_date': '03/01/2021',
        'current_price' : 210,
        'sold': 700,
        'vft_reserve': 300,
        'vite_reserve': 0.6
    },
    {
        '_id': '4',
        'name': 'vuilder_4',
        'image': '/images/empty-profile.png',
        'header': 'this is my header',
        'blog' : 'isque ac enim. Pellentesque ullamcorper ex ac nibh gravida aliquet non a sem.',
        'link': 'www.vuilder4.com',
        'minted': "false",
        'mint_date': 'Not Minted Yet',
        'current_price' : 0.003,
        'sold': 0,
        'vft_reserve': 1000,
        'vite_reserve': 0.002
    },
    {
        '_id': '5',
        'name': 'vuilder_5',
        'image': '/images/empty-profile.png',
        'header': 'this is my header',
        'blog' : 'isque ac enim. Pellentesque ullamcorper ex ac nibh gravida aliquet non a sem.',
        'link': 'www.vuilder5.com',
        'minted': "true",
        'mint_date': '27/06/2021',
        'current_price' : 102,
        'sold': 340,
        'vft_reserve': 660,
        'vite_reserve': 0.2
    },
    {
        '_id': '6',
        'name': 'vuilder_6',
        'image': '/images/empty-profile.png',
        'header': 'this is my header',
        'blog' : 'isque ac enim. Pellentesque ullamcorper ex ac nibh gravida aliquet non a sem.',
        'link': 'www.vuilder6.com',
        'minted': "false",
        'mint_date': 'Not Minted Yet',
        'current_price' : 0.003,
        'sold': 0,
        'vft_reserve': 1000,
        'vite_reserve': 0.002
    }
]