const data = [{
    "id":0,
    "asset":"ETH/USD",
    "img":"./img/ETH.svg"
},{
    "id":1,
    "asset":"BTC/USD",
    "img":"./img/BTC.svg"
},{
    "id":2,
    "asset":"BNB/USD",
    "img":"./img/BNB.svg"
},{
    "id":3,
    "asset":"LINK/USD",
    "img":"./img/LINK.svg"
},{
    "id":4,
    "asset":"BAT/USD",
    "img":"./img/BAT.svg"
},{
    "id":5,
    "asset":"TRX/USD",
    "img":"./img/TRX.svg"
},{
    "id":6,
    "asset":"ZRX/USD",
    "img":"./img/ZRX.svg"
},{
    "id":7,
    "asset":"XTZ/USD",
    "img":"./img/XTZ.svg"
},{
    "id":8,
    "asset":"XRP/USD",
    "img":"./img/XRP.svg"
}
]
export default data;